apiVersion: v2
name: grafana
description: Grafana
type: application
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/eformat/grafana-test
icon: https://avatars1.githubusercontent.com/u/68044996?s=200&v=4
maintainers:
- name: eformat
